package com.hand.hapexam.person.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.mybatis.annotation.Condition;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "person")
public class Person extends BaseDTO {
     @Id
     @GeneratedValue
     @Column
      private Long id;

    @Column
    @Condition(operator = "LIKE")
      private String name;
    @Column
      private String telephone;
    @Column
      private String email;
    @Column
      private String address;
    @Column
      private String gender;

      private Long parentFunctionId;

      private String enabledFlag;

      private Long functionSequence;


     public void setId(Long id){
         this.id = id;
     }

     public Long getId(){
         return id;
     }

     public void setName(String name){
         this.name = name;
     }

     public String getName(){
         return name;
     }

     public void setTelephone(String telephone){
         this.telephone = telephone;
     }

     public String getTelephone(){
         return telephone;
     }

     public void setEmail(String email){
         this.email = email;
     }

     public String getEmail(){
         return email;
     }

     public void setAddress(String address){
         this.address = address;
     }

     public String getAddress(){
         return address;
     }

     public void setGender(String gender){
         this.gender = gender;
     }

     public String getGender(){
         return gender;
     }

     public void setParentFunctionId(Long parentFunctionId){
         this.parentFunctionId = parentFunctionId;
     }

     public Long getParentFunctionId(){
         return parentFunctionId;
     }

     public void setEnabledFlag(String enabledFlag){
         this.enabledFlag = enabledFlag;
     }

     public String getEnabledFlag(){
         return enabledFlag;
     }

     public void setFunctionSequence(Long functionSequence){
         this.functionSequence = functionSequence;
     }

     public Long getFunctionSequence(){
         return functionSequence;
     }

     }
